In [1]:
import numpy as np

In [2]:
grid = [[0, 2, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 2],
        [5, 0, 3, 2, 4, 1],
        [2, 4, 1, 3, 0, 6],
        [3, 5, 0, 6, 0, 4],
        [6, 1, 0, 5, 2, 3]
        ]

In [15]:
def possible(y, x, n):
    global grid
    for i in range(0, 6):
        if grid[y][i] == n:
            return False

    for i in range(0, 6):
        if grid[i][x] == n:
            return False

    x0 = (x//3)*3
    y0 = (y//3)*3

    for i in range(0, 3):
        for j in range(0, 3):
            if grid[y0+i][x0+j] == n:
                return False

    return True

In [4]:
print(np.matrix(grid))

[[0 2 0 1 0 0]
 [0 0 0 0 0 2]
 [5 0 3 2 4 1]
 [2 4 1 3 0 6]
 [3 5 0 6 0 4]
 [6 1 0 5 2 3]]


In [16]:
def solve():
    global grid
    for y in range(6):
        for x in range(6):
            if grid[y][x] == 0:
                for n in range(1, 10):
                    if possible(y, x, n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return
    print(np.matrix(grid))

In [ ]:
[[9 2 8 1 7 5]
 [1 7 4 9 3 2]
 [5 6 3 2 4 1]
 [2 4 1 3 9 6]
 [3 5 7 6 8 4]
 [6 1 9 5 2 3]]

In [17]:
solv